### PR TITLE
done multiplication

### LINKED ISSUE #9: Complete the ```multiplication``` function
### **Task**
Complete the multiplication function in order to be able to multiply two numbers

### **Acceptance Criteria**

- when two numbers are passed into the function called ```multiplication```, then the operation is mathematically correct

### PR DESCRIPTION
**Pull request by heyseppy**

### CODE REVIEW

**Comment by heyseppy** [comment]
dude i did this so wrong bahahahahh can i delete this

**Review by cookies-xor-cream — COMMENTED** [review]
- Left a pass at the end of the function
- unexpected "hehehe"

**Review by cookies-xor-cream — APPROVED** [review]
I changed my mind on the "hehehe" and want to see if the pass will break anything (although I doubt it)

**Review by Antares4 — COMMENTED** [review]
not bad

**Pull request merged**
